import { DateObject } from "react-multi-date-picker"

import { v4 as uuid } from "uuid"

import {
  company as Company,
  ad as AD,
  category as Category,
  category_collection as Category_collection,
  city as City,
  province as Province,
  user as User,
  advantage as Advantage,
  location as Location,
} from "@prisma/client"

export const CategoriesData: Category[] = [
  { id: uuid(), name: "حسابدار / مالی و..", link: "accounting" },
  { id: uuid(), name: "معامله گر و تحلیل بازار های مالی", link: "trader" },
  { id: uuid(), name: "منابع انسانی", link: "humen-resources" },
  { id: uuid(), name: "فروش و بازاریابی - کارشناس و مدیر", link: "sales" },
  { id: uuid(), name: "سئو", link: "seo" },
  { id: uuid(), name: "برنامه نویس و توسعه نرم افزار", link: "developer" },
]

export const CategoryCollectionData: Category_collection[] = [
  {
    id: uuid(),
    category_id: CategoriesData[0].id,
    name: "مدیر مالی",
    link: "finacial-manager",
  },
  {
    id: uuid(),
    category_id: CategoriesData[0].id,
    name: "کمک حسابدار",
    link: "accounting-assistant",
  },
  { id: uuid(), category_id: CategoriesData[0].id, name: "حسابرس", link: "auditor" },

  {
    id: uuid(),
    category_id: CategoriesData[5].id,
    name: "برنامه نویس Node.js",
    link: "nodejs",
  },
  {
    id: uuid(),
    category_id: CategoriesData[5].id,
    name: "برنامه نویس فرانت اند",
    link: "frontend",
  },
  { id: uuid(), category_id: CategoriesData[5].id, name: "برنامه نویس react", link: "react" },
  {
    id: uuid(),
    category_id: CategoriesData[5].id,
    name: "برنامه نویس اندروید",
    link: "android",
  },
]

export const ProvincesData: Province[] = [
  { id: uuid(), name: "تهران" },
  { id: uuid(), name: "خراسان رضوی" },
  { id: uuid(), name: "مازندران" },
]

export const CitiesData: City[] = [
  { id: uuid(), province_id: ProvincesData[0].id, name: "شهریار" },
  { id: uuid(), province_id: ProvincesData[0].id, name: "کمالشهر" },
  { id: uuid(), province_id: ProvincesData[0].id, name: "پرند" },

  { id: uuid(), province_id: ProvincesData[1].id, name: "مشهد" },
  { id: uuid(), province_id: ProvincesData[1].id, name: "نیشابور" },

  { id: uuid(), province_id: ProvincesData[2].id, name: "ساری" },
  { id: uuid(), province_id: ProvincesData[2].id, name: "چالوس" },
]

export const LocationsData: Location[] = [
  { id: uuid(), city_id: CitiesData[3].id, address: "سعادت آباد" },
  { id: uuid(), city_id: CitiesData[2].id, address: "نبش پرند 12" },
  { id: uuid(), city_id: CitiesData[5].id, address: "خیابان پاستور" },
  { id: uuid(), city_id: CitiesData[6].id, address: "خیابان فردوسی شمالی" },
  { id: uuid(), city_id: CitiesData[1].id, address: "کمالشهر 16" },
]

export const CompaniesData: Company[] = [
  {
    id: uuid(),
    created_at: new Date(),
    name: "ایرانسل",
    location_id: LocationsData[0].id,
    logo: "1_irancell.png",
    score_company: 4.3,
    score_popularity: 4.6,
    score_experience_of_job_seekers: 5,
    score_responsiveness: 2,
    website: "https://irancell.ir",
    description: "متن تستی برای شرکت ایرانسل",
    slogan: "متن تستی برای شعار شرکت ایرانسل",
    organization_employ: 3,
    type_of_activity: "متن تستی نوع فعالیت برای شرکت ایرانسل",
    industry: "متن تستی صنعت برای شرکت ایرانسل",
    established_year: new Date(new DateObject().format()),
  },
  {
    id: uuid(),
    created_at: new Date(),
    name: "دیجی کالا",
    location_id: LocationsData[1].id,
    logo: "2_digikala.svg",
    score_company: 4.3,
    score_popularity: 4.6,
    score_experience_of_job_seekers: 5,
    score_responsiveness: 2,
    website: "https://www.digikala.com",
    description: "متن تستی برای شرکت دیجی کالا",
    slogan: "متن تستی برای شعار شرکت دیجی کالا",
    organization_employ: 3,
    type_of_activity: "متن تستی نوع فعالیت برای شرکت دیجی کالا",
    industry: "متن تستی صنعت برای شرکت دیجی کالا",
    established_year: new Date(new DateObject().format()),
  },
  {
    id: uuid(),
    created_at: new Date(),
    name: "ترب",
    location_id: LocationsData[2].id,
    logo: "3_trob.svg",
    score_company: 4.3,
    score_popularity: 4.6,
    score_experience_of_job_seekers: 5,
    score_responsiveness: 2,
    website: "https://torob.com/",
    description: "متن تستی برای شرکت ترب",
    slogan: "متن تستی برای شعار شرکت ترب",
    organization_employ: 3,
    type_of_activity: "متن تستی نوع فعالیت برای شرکت ترب",
    industry: "متن تستی صنعت برای شرکت ترب",
    established_year: new Date(new DateObject().format()),
  },
  {
    id: uuid(),
    created_at: new Date(),
    name: "اسنپ",
    location_id: LocationsData[3].id,
    logo: "4_snapp.svg",
    score_company: 4.3,
    score_popularity: 4.6,
    score_experience_of_job_seekers: 5,
    score_responsiveness: 2,
    website: "https://snapp.ir/",
    description: "متن تستی برای شرکت اسنپ",
    slogan: "متن تستی برای شعار شرکت اسنپ",
    organization_employ: 3,
    type_of_activity: "متن تستی نوع فعالیت برای شرکت اسنپ",
    industry: "متن تستی صنعت برای شرکت اسنپ",
    established_year: new Date(new DateObject().format()),
  },
  {
    id: uuid(),
    created_at: new Date(),
    name: "دیوار",
    location_id: LocationsData[4].id,
    logo: "5_divar.svg",
    score_company: 4.3,
    score_popularity: 4.6,
    score_experience_of_job_seekers: 5,
    score_responsiveness: 2,
    website: "https://divar.ir/",
    description: "متن تستی برای شرکت دیوار",
    slogan: "متن تستی برای شعار شرکت دیوار",
    organization_employ: 3,
    type_of_activity: "متن تستی نوع فعالیت برای شرکت دیوار",
    industry: "متن تستی صنعت برای شرکت دیوار",
    established_year: new Date(new DateObject().format()),
  },
]

export const UsersData: User[] = [
  {
    id: "1",
    company_id: CompaniesData[0].id,
    email: "sobhan@gmail.com",
    password: process.env.NEXT_PUBLIC_SOBHAN_PASS as string,
    created_at: new Date(),
  },
  {
    id: "2",
    company_id: CompaniesData[1].id,
    email: "mahtab@gmail.com",
    password: process.env.NEXT_PUBLIC_MAHTAB_PASS as string,
    created_at: new Date(),
  },
  {
    id: "3",
    company_id: CompaniesData[2].id,
    email: "farzad@gmail.com",
    password: process.env.NEXT_PUBLIC_FARZAD_PASS as string,
    created_at: new Date(),
  },
  {
    id: "4",
    company_id: CompaniesData[3].id,
    email: "mehrdad@gmail.com",
    password: process.env.NEXT_PUBLIC_MEHRDAD_PASS as string,
    created_at: new Date(),
  },
  {
    id: "5",
    company_id: CompaniesData[4].id,
    email: "amir@gmail.com",
    password: process.env.NEXT_PUBLIC_AMIR_PASS as string,
    created_at: new Date(),
  },
]

export const AdvantageData: Advantage[] = [
  { id: uuid(), type: "وام" },
  { id: uuid(), type: "پارکینگ" },
  { id: uuid(), type: "پاداش" },
  { id: uuid(), type: "سرویس رفت و برگشت" },
]

export const AdsData: AD[] = [
  {
    company_id: CompaniesData[0].id,
    id: uuid(),
    name: "متخصص next js",
    price: { max: 0, min: 200000000 },
    work_time: "از شنبه تا چهارشنبه ساعت 8 صبح تا 12 ظهر",
    travel_benefits: "سفر به کیش",
    age: { max: 0, min: 19 },
    edicational_level: ["دیپلم شبکه و نرم افزار"],
    key_indicator: ["یک سال سابقه کار با react", "دو سال سابقه کار"],
    software_skills: [
      "react - متوسط",
      "next js - متوسط",
      "js - متخصص",
      "html",
      "css",
      "react hook form",
      "axios",
      "zod",
      "prisma",
      "shadcn ui",
      "tailwind",
      "bootstrap",
      "typescript",
      "sass",
      "postman",
      "npm",
      "lodash",
      "figma",
    ],
    tags: [CategoryCollectionData[0], CategoryCollectionData[1]],
    facilities: [AdvantageData[0], AdvantageData[1], AdvantageData[2]],
    gender: "MALE",
    seniority_level: "EXPERT",
    cooperation_type: "FULL_TIME",
    disabledPeople: false,
    important: true,
    itern: false,
    militaryOrder: false,
    response: false,
    telecommuting: false,
    created_at: new Date(),
  },
  {
    company_id: CompaniesData[0].id,
    id: uuid(),
    name: "برنامه نویس react - ری اکت",
    price: { max: 0, min: 200000000 },
    work_time: "از شنبه تا چهارشنبه ساعت 8 صبح تا 12 ظهر",
    travel_benefits: "سفر به کیش",
    age: { max: 0, min: 19 },
    edicational_level: ["دیپلم شبکه و نرم افزار"],
    key_indicator: ["یک سال سابقه کار با react", "دو سال سابقه کار"],
    software_skills: [
      "react - متوسط",
      "next js - متوسط",
      "js - متخصص",
      "html",
      "css",
      "react hook form",
      "axios",
      "zod",
      "prisma",
      "shadcn ui",
      "tailwind",
      "bootstrap",
      "typescript",
      "sass",
      "postman",
      "npm",
      "lodash",
      "figma",
    ],
    tags: [CategoryCollectionData[0], CategoryCollectionData[3]],
    facilities: [AdvantageData[1], AdvantageData[2]],
    gender: "MALE",
    seniority_level: "EXPERT",
    cooperation_type: "FULL_TIME",
    disabledPeople: false,
    important: true,
    itern: false,
    militaryOrder: false,
    response: false,
    telecommuting: true,
    created_at: new Date(),
  },
  {
    company_id: CompaniesData[0].id,
    id: uuid(),
    name: "توسعه دهنده فرانت اند",
    price: { max: 70_000_000, min: 10_000_000 },
    work_time: "از شنبه تا چهارشنبه ساعت 8 صبح تا 12 ظهر",
    travel_benefits: "سفر به کیش",
    age: { max: 0, min: 19 },
    edicational_level: ["دیپلم شبکه و نرم افزار"],
    key_indicator: ["یک سال سابقه کار با react", "دو سال سابقه کار"],
    software_skills: [
      "react - متوسط",
      "next js - متوسط",
      "js - متخصص",
      "html",
      "css",
      "react hook form",
      "axios",
      "zod",
      "prisma",
      "shadcn ui",
      "tailwind",
      "bootstrap",
      "typescript",
      "sass",
      "postman",
      "npm",
      "lodash",
      "figma",
    ],
    tags: [CategoryCollectionData[0], CategoryCollectionData[2]],
    facilities: [AdvantageData[1]],
    gender: "MALE",
    seniority_level: "EXPERT",
    cooperation_type: "FULL_TIME",
    disabledPeople: false,
    important: true,
    itern: true,
    militaryOrder: true,
    response: false,
    telecommuting: false,
    created_at: new Date(),
  },
]
